### ISSUE TITLE
[BUG] OpenSearch Dashboards Alerting Action Preview

### ISSUE THREAD

**Issue by wynnchel** [opensearch-project/alerting-dashboards-plugin#152]
**Describe the bug**

The mustache preview of `ctx.results[0].hits.hits` is broken and will not be displayed in the message preview.

**To Reproduce**
1. Go to Alerting and open a query with the method _Extraction query editor_
2. Add a sample query
3. Scroll down to 'Actions'
4. Add sample values

```
Monitor {{ctx.monitor.name}} just entered alert status. Please investigate the issue.
  - Trigger: {{ctx.trigger.name}}
  - Severity: {{ctx.trigger.severity}}
  - Period start: {{ctx.periodStart}}
  - Period end: {{ctx.periodEnd}}

{{#ctx.results[0].hits.hits}}
{{_source.summary.up}}
{{/ctx.results[0].hits.hits}}
```

The upper 4 values will be previewed if set. The results part will NOT be previewed. If one sends a test email the contents will be correct.

**Expected behavior**
The contents of the results will be previewed correctly.

**OpenSearch Version**
Docker 1.1.0

```
REPOSITORY                                TAG            IMAGE ID       CREATED         SIZE
opensearchproject/opensearch              1.1.0          6394bbe93612   6 weeks ago     835MB
```

**Dashboards Version**
Docker 1.1.0

```
REPOSITORY                                TAG            IMAGE ID       CREATED         SIZE
opensearchproject/opensearch-dashboards   1.1.0          ce0ea078fdfb   6 weeks ago     897MB
```

**Plugins**

Default

**Screenshots**

![2021-11-18-225740_670x602_scrot](https://user-images.githubusercontent.com/48353644/142503692-1ba6568d-bc7b-4fc0-b707-85e289948143.png)

![2021-11-18-225800_327x181_scrot](https://user-images.githubusercontent.com/48353644/142503693-edf408ab-e631-47d4-a899-40f9743dc9d1.png)

**Additional context**

None

**Comment by wynnchel** [comment]
Thank you, didn't see this repository. I've uploaded a wrong screenshot as well, the first one doesn't show the configuration of the 2nd screenshot (email). I'll fix this asap.

**Comment by sikhote** [comment]
A PR for this is created, but I also wanted to drop a comment about the Mustache code being used. Once the correct data was available, in order to access the inner data I needed to access data from an array slightly different, like this:

{{#ctx.results.0.hits.hits.0}}
{{_source.agent}}
{{/ctx.results.0.hits.hits.0}}

The main difference being the `.0` rather than `[0]`.

**Comment by AWSHurneyt** [comment]
Closing this issue as PR https://github.com/opensearch-project/alerting-dashboards-plugin/pull/334 has been merged. As discussed in that PR, there is a known issue with some of the variables in `ctx` which results from the alerting backend. That issue is being tracked in this issue https://github.com/opensearch-project/alerting/issues/200 in the backend repo, and there is currently a PR published to address it.
